/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.bastianelli.personale.burraco.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Game service. Represents a row in the &quot;BURRACO_Game&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.bastianelli.personale.burraco.model.impl.GameModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.bastianelli.personale.burraco.model.impl.GameImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Game
 * @generated
 */
@ProviderType
public interface GameModel
	extends BaseModel<Game>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a game model instance should use the {@link Game} interface instead.
	 */

	/**
	 * Returns the primary key of this game.
	 *
	 * @return the primary key of this game
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this game.
	 *
	 * @param primaryKey the primary key of this game
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this game.
	 *
	 * @return the uuid of this game
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this game.
	 *
	 * @param uuid the uuid of this game
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the game ID of this game.
	 *
	 * @return the game ID of this game
	 */
	public long getGameId();

	/**
	 * Sets the game ID of this game.
	 *
	 * @param gameId the game ID of this game
	 */
	public void setGameId(long gameId);

	/**
	 * Returns the group ID of this game.
	 *
	 * @return the group ID of this game
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this game.
	 *
	 * @param groupId the group ID of this game
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this game.
	 *
	 * @return the company ID of this game
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this game.
	 *
	 * @param companyId the company ID of this game
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this game.
	 *
	 * @return the user ID of this game
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this game.
	 *
	 * @param userId the user ID of this game
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this game.
	 *
	 * @return the user uuid of this game
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this game.
	 *
	 * @param userUuid the user uuid of this game
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this game.
	 *
	 * @return the user name of this game
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this game.
	 *
	 * @param userName the user name of this game
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this game.
	 *
	 * @return the create date of this game
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this game.
	 *
	 * @param createDate the create date of this game
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this game.
	 *
	 * @return the modified date of this game
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this game.
	 *
	 * @param modifiedDate the modified date of this game
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the state of this game.
	 *
	 * @return the state of this game
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this game.
	 *
	 * @param state the state of this game
	 */
	public void setState(String state);

	/**
	 * Returns the result of this game.
	 *
	 * @return the result of this game
	 */
	@AutoEscape
	public String getResult();

	/**
	 * Sets the result of this game.
	 *
	 * @param result the result of this game
	 */
	public void setResult(String result);

	/**
	 * Returns the description of this game.
	 *
	 * @return the description of this game
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this game.
	 *
	 * @param description the description of this game
	 */
	public void setDescription(String description);

	/**
	 * Returns the opponent ID of this game.
	 *
	 * @return the opponent ID of this game
	 */
	public long getOpponentId();

	/**
	 * Sets the opponent ID of this game.
	 *
	 * @param opponentId the opponent ID of this game
	 */
	public void setOpponentId(long opponentId);

	/**
	 * Returns the score of this game.
	 *
	 * @return the score of this game
	 */
	public int getScore();

	/**
	 * Sets the score of this game.
	 *
	 * @param score the score of this game
	 */
	public void setScore(int score);

	/**
	 * Returns the opponent score of this game.
	 *
	 * @return the opponent score of this game
	 */
	public int getOpponentScore();

	/**
	 * Sets the opponent score of this game.
	 *
	 * @param opponentScore the opponent score of this game
	 */
	public void setOpponentScore(int opponentScore);

}